# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazytrack" do
  name "lazytrack"
  desc "Terminal UI for managing YouTrack issues, inspired by lazygit"
  homepage "https://github.com/traffiqq/lazyTrack"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazytrack"

  on_macos do
    on_intel do
      url "https://github.com/traffiqq/lazyTrack/releases/download/v#{version}/lazyTrack_#{version}_darwin_amd64.tar.gz"
      sha256 "dfc814dc4fdbe61849e447220602acb34c816ff36fe644344dd5c60d49a1fcb7"
    end
    on_arm do
      url "https://github.com/traffiqq/lazyTrack/releases/download/v#{version}/lazyTrack_#{version}_darwin_arm64.tar.gz"
      sha256 "b5465964e518f2f3c47f19f794161475f4e676140b2725ba3ec1575df1dea0f3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/traffiqq/lazyTrack/releases/download/v#{version}/lazyTrack_#{version}_linux_amd64.tar.gz"
      sha256 "63067038c84f0d037595afe51c9b2790b7244a4f4045c0bd61c4628f6a6b32e7"
    end
    on_arm do
      url "https://github.com/traffiqq/lazyTrack/releases/download/v#{version}/lazyTrack_#{version}_linux_arm64.tar.gz"
      sha256 "f2ee633069be205060eb1ebba00893a963de5c38ea1712c07399e51f549f1582"
    end
  end

  # No zap stanza required
end
